baseURL: http://example.org/
languageCode: en-us
title: Boards & Bites
theme: "paperMod"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Longboard adventures featuring food & drink"
    author: ["John Kiernan", "Grace Kelly"]
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Board & Bites
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Food, Drink and Longboard Adventures"
        Content:
            "Welcome to Boards & Bites -- a weird blog where two longboarding noobs catalog their gustatory exploits.
            Read on to discover more about\n
            - 🍗  Restaurants, eateries and picnic food\n
            - 🍺  Tasty brews and beverages\n
            - 😭  The many aches and pains of amateur longboarders"
    socialIcons:
        - name: instagram
          url: "https://instagram.com"
